# Generated by Django 2.2.10 on 2022-03-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_diem', models.CharField(max_length=250)),
                ('thanh_pho', models.CharField(max_length=200)),
                ('khach_san', models.TextField(blank=True, max_length=200)),
                ('nha_hang', models.TextField(blank=True, max_length=200)),
                ('quan_an', models.TextField(blank=True, max_length=200)),
                ('giai_tri', models.TextField(blank=True, max_length=200)),
                ('ghi_chu', models.TextField(blank=True, max_length=300)),
            ],
        ),
    ]
